"""Loading the ETHOS.Data catalogue and its Frictionless Data Packages.

Loading is **lazy**: ``load_catalog`` reads only ``datacatalog.json`` -- the
small index -- and pulls a dataset's ``datapackage.json`` the first time
something actually asks for its files.  That matters once a dataset is large:
the ERA5 inventory alone is ~64 MB and 170k resources, and without laziness
every ``ethos-data`` invocation would download and parse it just to answer a
question about a different dataset.

Everything the index already knows -- byte total, file count, access class,
remote prefix, licence status -- is answered from the index and never triggers a
fetch, so ``ethos-data list`` and access checks stay free.

A large dataset may additionally be **sharded**: its ``datapackage.json`` carries
an ``ethos:shards`` index instead of a ``resources`` array, and the inventory is
split across ``manifests/<prefix>.json`` files, one per directory prefix of
``ethos:shard_depth`` segments.  Selecting ``4/6/5/**`` then parses the 664
resources of that one tile rather than all 170k.  Sharding is transparent: ask
for ``.resources`` and every shard is pulled in, exactly as before.
"""

from __future__ import annotations

import fnmatch
import gzip
import hashlib
import json
import os
import re
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

__all__ = ["Catalog", "Dataset", "Resource", "load_catalog"]

#: Refs that move.  A catalogue fetched from one of these must not be cached
#: forever, or development against the internal catalogue silently goes stale.
_MOVING_REF = re.compile(r"/(?:refs/heads/)?(?:main|master|HEAD|latest|dev|develop)/")

NO_CACHE_ENV = "ETHOS_CATALOG_NO_CACHE"


def _pinned(url: str) -> bool:
    """Whether this URL names an immutable version, and may be cached forever."""
    if os.environ.get(NO_CACHE_ENV):
        return False
    return not _MOVING_REF.search(url)


def _cache_path(url: str) -> Path:
    # Imported here: config pulls in platformdirs, and catalog.py is imported by
    # tooling that only wants the dataclasses.
    from .config import resolve_cache_dir

    digest = hashlib.sha256(url.encode()).hexdigest()[:16]
    return resolve_cache_dir().value / ".catalog" / digest / url.rsplit("/", 1)[-1]


def _read(location: str) -> tuple[str, str]:
    """Return (text, base location) for a local path or an http(s) URL.

    Descriptors fetched from a version-pinned URL are cached on disk and reused,
    and the request asks for gzip -- these files compress ~40x, and without the
    header urllib sends ``Accept-Encoding: identity``.
    """
    if not location.startswith(("http://", "https://")):
        path = Path(location).expanduser().resolve()
        return path.read_text(), path.parent.as_posix() + "/"

    base = location.rsplit("/", 1)[0] + "/"
    cacheable = _pinned(location)
    cached = _cache_path(location) if cacheable else None

    if cached is not None and cached.is_file():
        return cached.read_text(), base

    request = urllib.request.Request(location, headers={"Accept-Encoding": "gzip"})
    with urllib.request.urlopen(request, timeout=60) as response:
        raw = response.read()
        if response.headers.get("Content-Encoding") == "gzip":
            raw = gzip.decompress(raw)
    text = raw.decode("utf-8")

    if cached is not None:
        cached.parent.mkdir(parents=True, exist_ok=True)
        # Write-then-rename: two processes racing must never see a half file.
        temporary = cached.with_suffix(cached.suffix + f".{os.getpid()}.part")
        temporary.write_text(text)
        temporary.replace(cached)
    return text, base


#: Shard holding files that sit at the dataset root, above any shard directory.
ROOT_SHARD = "_root"

#: Declares what kind of catalogue a descriptor is, so tools and error messages
#: never have to infer it from which files happen to be lying around.
ROLE_KEY = "ethos:catalog_role"
#: Hand-written, holds dataset.yaml and source_dir; the thing you edit and upload from.
ROLE_SOURCE = "source"
#: Generated by `ethos-data catalog publish`; metadata only, overwritten on every publish.
ROLE_PUBLISHED = "published"
CATALOG_ROLES = (ROLE_SOURCE, ROLE_PUBLISHED)


def describe_catalog(descriptor: dict, location: str = "") -> str:
    """A short human name for a catalogue, for use in error messages.

    Both catalogues share a ``name`` -- the public one is a subset view of the
    same catalogue, not a different one -- so the role is what distinguishes
    them, and it is the thing a reader needs to know when a dataset is absent.
    """
    name = descriptor.get("name") or "catalogue"
    role = descriptor.get(ROLE_KEY)
    label = f"{role} catalogue {name!r}" if role else f"catalogue {name!r}"
    return f"{label} ({location})" if location else label


class UnknownDataset(KeyError):
    """A collection names a dataset this catalogue does not describe.

    Usually a withdrawn dataset rather than a typo: a collections file pinned to
    an older catalogue keeps working, and only breaks when it is repointed at a
    newer one that no longer publishes what it asks for. Subclasses KeyError so
    existing ``except KeyError`` handlers keep working; the CLI catches this
    specific type so a genuine bug still surfaces as a traceback.
    """


def shard_key(relative_path: str, depth: int) -> str:
    """Which shard a resource path belongs to.

    Keyed on the *directory* prefix, so every file in a directory lands in the
    same shard as its neighbours -- which is what makes shapefile sidecars and
    a tile's variables resolvable without touching a second shard.
    """
    directories = relative_path.split("/")[:-1]
    return "/".join(directories[:depth]) or ROOT_SHARD


def _shard_could_match(prefix: str, pattern: str) -> bool:
    """Could any path under ``prefix`` match ``pattern``?

    Conservative by construction: it may say yes for a shard that turns out to
    contain nothing matching (the caller filters properly afterwards), but it
    must never say no for a shard that does. Saying no wrongly would silently
    drop files from a collection, which is far worse than one extra fetch.
    """
    parts = [] if prefix == ROOT_SHARD else prefix.split("/")
    patterns = pattern.split("/")
    if not parts:
        # The root shard is the one whose files have no directory component at
        # all, so only a single-segment pattern can name one -- or a pattern
        # starting with ``**``, which absorbs zero segments. The general rule
        # below cannot express this: it reasons about files sitting *below* a
        # prefix directory, and these sit at the top instead. Without the
        # distinction every selection drags the root shard in, whatever it asked
        # for.
        return len(patterns) == 1 or patterns[0] == "**"
    while parts:
        if not patterns:
            # The pattern describes a shallower path than this shard's prefix.
            return False
        head = patterns[0]
        if head == "**":
            return True  # absorbs any number of segments, including these
        if not fnmatch.fnmatchcase(parts[0], head):
            return False
        parts, patterns = parts[1:], patterns[1:]
    # Files in a shard sit *below* its prefix directory, so a pattern that ran
    # out exactly at the prefix is one segment too short to match any of them.
    return bool(patterns)


def _join(base: str, relative: str) -> str:
    if base.startswith(("http://", "https://")):
        return urllib.parse.urljoin(base, relative)
    return (Path(base) / relative).as_posix()


@dataclass(frozen=True)
class Resource:
    """One file in a dataset, as described by the Data Package descriptor."""

    dataset: str
    name: str
    path: str
    bytes: int
    hash: str
    mediatype: str
    sidecars: tuple[str, ...] = ()

    @property
    def key(self) -> str:
        """Logical identity: stable across tools, and the cache path."""
        return f"{self.dataset}/{self.path}"


@dataclass
class Dataset:
    """A dataset in the catalogue, loaded on demand.

    ``entry`` is the cheap row from ``datacatalog.json``.  ``descriptor`` and
    ``resources`` fetch the dataset's ``datapackage.json`` on first access; the
    properties above them answer from ``entry`` and never do.
    """

    name: str
    title: str
    entry: dict = field(default_factory=dict)
    base: str = ""
    _descriptor: dict | None = field(default=None, repr=False)
    _resources: dict[str, Resource] = field(default_factory=dict, repr=False)
    # Keep licence/provenance extensions without retaining a duplicate full
    # inventory: large shards can contain millions of ordinary Resource rows.
    _resource_extras: dict[str, dict] = field(default_factory=dict, repr=False)
    _shards: dict[str, dict] = field(default_factory=dict, repr=False)
    _loaded_shards: set[str] = field(default_factory=set, repr=False)
    _shard_depth: int = field(default=0, repr=False)
    _package_base: str = field(default="", repr=False)

    # -- answered from the index; never triggers a fetch ---------------------

    @property
    def loaded(self) -> bool:
        """Whether the complete inventory is in memory."""
        return self._descriptor is not None and not self.pending_shards

    @property
    def sharded(self) -> bool:
        return bool(self._shards)

    @property
    def pending_shards(self) -> list[str]:
        """Shards described by the descriptor but not yet fetched."""
        return sorted(set(self._shards) - self._loaded_shards)

    @property
    def namespace(self) -> bool:
        """Whether this is a family name rather than a dataset with files.

        A namespace has members -- ``reskit-test-data`` for
        ``reskit-test-data/era5`` and its siblings -- and nothing of its own to
        download. Answered from the index row, so asking never costs a fetch.
        """
        return bool(self.entry.get("ethos:namespace", False))

    @property
    def access(self) -> str:
        return self.entry.get("ethos:access", "public")

    @property
    def visibility(self) -> str:
        return self.entry.get("ethos:visibility", "public")

    @property
    def total_bytes(self) -> int:
        if "ethos:total_bytes" in self.entry:
            return self.entry["ethos:total_bytes"]
        return sum(r.bytes for r in self.resources.values())

    @property
    def file_count(self) -> int:
        if "ethos:file_count" in self.entry:
            return self.entry["ethos:file_count"]
        return len(self.resources)

    @property
    def remote_prefix(self) -> str:
        if "ethos:remote_prefix" in self.entry:
            return self.entry["ethos:remote_prefix"]
        return self.descriptor.get("ethos:remote_prefix", self.name)

    @property
    def license_status(self) -> str:
        """"resolved" once somebody has read the upstream terms.

        Promoted into the index by build_manifest.py so that listing a catalogue
        does not have to load every descriptor to warn about licensing.
        """
        if "ethos:license_status" in self.entry:
            return self.entry["ethos:license_status"]
        if self.descriptor.get("licenses"):
            return "resolved"
        return self.descriptor.get("ethos:license_status", "unknown")

    # -- these pull the datapackage in --------------------------------------

    @property
    def descriptor(self) -> dict:
        """The datapackage.json.  Cheap for a sharded dataset -- no inventory."""
        if self._descriptor is None:
            self.load()
        return self._descriptor

    @property
    def resources(self) -> dict[str, Resource]:
        """The complete inventory.  For a sharded dataset this pulls every shard.

        Prefer :meth:`resources_matching` where the patterns are known -- that is
        the whole reason sharding exists.
        """
        self.load()
        self._load_shards(self.pending_shards)
        return self._resources

    def load(self) -> None:
        """Fetch and parse this dataset's datapackage.json.  Idempotent.

        For a sharded dataset this reads only the shard index; the inventory
        itself arrives shard by shard.
        """
        if self._descriptor is not None:
            return
        if not self.entry.get("path"):
            raise ValueError(
                f"dataset {self.name!r} has no 'path' in the catalogue index, so its "
                "file inventory cannot be located."
            )
        location = _join(self.base, self.entry["path"])
        package = json.loads(_read(location)[0])
        # Shard paths are relative to the dataset directory, not the catalogue root.
        self._package_base = location.rsplit("/", 1)[0] + "/"
        self._shard_depth = int(package.get("ethos:shard_depth", 0))
        self._shards = {entry["prefix"]: entry for entry in package.get("ethos:shards", [])}
        self._descriptor = package
        if not self._shards:
            self._absorb(package.get("resources", []))

    def resources_matching(self, patterns: list[str]) -> dict[str, Resource]:
        """Resources from the shards that could possibly match ``patterns``.

        Returns a superset -- the caller still globs properly. On an unsharded
        dataset this is just the whole inventory.
        """
        self.load()
        if not self._shards:
            return self._resources
        wanted = [
            prefix
            for prefix in self._shards
            if any(_shard_could_match(prefix, pattern) for pattern in patterns)
        ]
        self._load_shards(wanted)
        return self._resources

    def resource_at(self, path: str) -> Resource | None:
        """One resource by path, loading only the shard that can hold it.

        Used for shapefile sidecars, which live beside their .shp and therefore
        always land in the same shard -- no second fetch in practice.
        """
        self.load()
        if self._shards:
            key = shard_key(path, self._shard_depth)
            if key in self._shards:
                self._load_shards([key])
        return self._resources.get(path)

    def resource_descriptor(self, path: str) -> dict | None:
        """One original resource record, including licence/provenance overrides.

        Loads only the shard that can contain this resource, as resource_at
        does. Returning a copy lets snapshot exporters retain extension fields
        without mutating the canonical inventory.
        """
        resource = self.resource_at(path)
        if resource is None:
            return None
        record = {
            "name": resource.name, "path": resource.path, "bytes": resource.bytes,
            "hash": resource.hash, "mediatype": resource.mediatype,
            **self._resource_extras.get(path, {}),
        }
        if resource.sidecars:
            record["ethos:sidecars"] = list(resource.sidecars)
        return record

    def _load_shards(self, prefixes: list[str]) -> None:
        for prefix in prefixes:
            if prefix in self._loaded_shards:
                continue
            entry = self._shards[prefix]
            shard = json.loads(_read(_join(self._package_base, entry["path"]))[0])
            self._absorb(shard.get("resources", []))
            self._loaded_shards.add(prefix)

    def _absorb(self, items: list[dict]) -> None:
        for item in items:
            extras = {key: value for key, value in item.items()
                      if key not in {"name", "path", "bytes", "hash", "mediatype", "ethos:sidecars"}}
            if extras:
                self._resource_extras[item["path"]] = extras
            self._resources[item["path"]] = Resource(
                dataset=self.name,
                name=item["name"],
                path=item["path"],
                bytes=item["bytes"],
                hash=item["hash"],
                mediatype=item.get("mediatype", "application/octet-stream"),
                sidecars=tuple(item.get("ethos:sidecars", ())),
            )


@dataclass
class Catalog:
    location: str
    descriptor: dict
    datasets: dict[str, Dataset]

    @property
    def name(self) -> str:
        return self.descriptor.get("name", "")

    @property
    def role(self) -> str:
        """``source``, ``published``, or "" for a catalogue predating the key."""
        return self.descriptor.get(ROLE_KEY, "")

    @property
    def publication_url(self) -> str:
        """Base URL for bytes, honouring a local override.

        Defaults to whatever the catalogue declares; ETHOS_PUBLICATION_URL or a
        `publication_url` config key can point at a different DESY door without
        the catalogue changing.
        """
        from .config import resolve_publication_url

        default = self.descriptor.get("ethos:publication_url", "")
        return resolve_publication_url(default)[0].rstrip("/")

    def members_of(self, name: str) -> list[Dataset]:
        """The datasets that carry files under a family name, innermost included.

        ``reskit-test-data`` yields its members; ``reskit-test-data/era5`` yields
        itself. Nested namespaces are skipped -- only things with an inventory
        come back -- so a caller can treat the result as "what to fetch".
        """
        prefix = f"{name}/"
        members = [
            dataset for key, dataset in self.datasets.items()
            if (key == name or key.startswith(prefix)) and not dataset.namespace
        ]
        return sorted(members, key=lambda d: d.name)

    def matching_datasets(self, pattern: str) -> list[Dataset]:
        """Datasets a collections file's ``dataset:`` field selects.

        An exact name wins outright, and a namespace name expands to its members
        -- which is what makes a family usable as one thing. Otherwise the string
        is treated as a glob over dataset names, so ``reskit-test-data/*`` picks
        the members explicitly and ``*-landcover`` picks across families.
        """
        from .selection import path_matches

        if pattern in self.datasets:
            found = self.members_of(pattern)
            if found:
                return found
            # Named exactly, but it is an empty namespace. Return it so the
            # caller's own "matched nothing" reporting fires, rather than
            # pretending the name was unknown.
            return [self.datasets[pattern]]
        matched = [
            dataset for key, dataset in self.datasets.items()
            if not dataset.namespace and path_matches(key, pattern)
        ]
        if matched:
            return sorted(matched, key=lambda d: d.name)
        # No match at all: let dataset() raise, so the error names the catalogue
        # and lists what it does have.
        return [self.dataset(pattern)]

    def dataset(self, name: str) -> Dataset:
        try:
            return self.datasets[name]
        except KeyError:
            known = ", ".join(sorted(self.datasets)) or "<none>"
            where = describe_catalog(self.descriptor, self.location)
            hint = ""
            if self.role == ROLE_PUBLISHED:
                # By far the likeliest cause: it was published once and later
                # withdrawn, so the collections file is not wrong, just newer
                # than the catalogue it is pointed at -- or older than it.
                hint = ("\nIf it used to exist, it has been withdrawn from publication. "
                        "Pin an older catalogue, or ask the maintainers to republish it.")
            raise UnknownDataset(
                f"unknown dataset {name!r}: the {where} does not describe it.\n"
                f"It has: {known}.{hint}"
            ) from None

    def base_url_for(self, dataset: Dataset) -> str:
        """Root under which this dataset's resource paths resolve.

        Single point of URL construction, so a per-dataset override (a mirror)
        only has to be honoured here.
        """
        return f"{self.publication_url}/{dataset.remote_prefix}/"

    def url_for(self, resource: Resource) -> str:
        return self.base_url_for(self.dataset(resource.dataset)) + resource.path

    def load_all(self) -> None:
        """Force every descriptor in.  For catalogue validation tooling only."""
        for dataset in self.datasets.values():
            dataset.load()


def load_catalog(location: str) -> Catalog:
    """Load a datacatalog.json.  Dataset inventories are fetched on first use.

    ``location`` is a local path or an http(s) URL pointing at datacatalog.json.
    """
    text, base = _read(location)
    descriptor = json.loads(text)

    datasets = {
        entry["name"]: Dataset(
            name=entry["name"],
            title=entry.get("title", ""),
            entry=entry,
            base=base,
        )
        for entry in descriptor.get("datasets", [])
    }
    return Catalog(location=location, descriptor=descriptor, datasets=datasets)
